cache: bundler
language: ruby
env:
  - "BOOTBOOT_TEST_BUNDLER_VERSION=1.17.3"
  - "BOOTBOOT_TEST_BUNDLER_VERSION=2.0.2"
  - "BOOTBOOT_TEST_BUNDLER_VERSION=2.1.4"
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
before_install:
  - yes | gem update --system --force
  - gem install bundler -v "$BOOTBOOT_TEST_BUNDLER_VERSION"
script:
  - bundle exec rubocop --config .rubocop.yml
  - bundle exec rake test
notifications:
  email: false
